### PR TITLE
Align BGP error code printing with IANA registry

### PR DESCRIPTION
**Pull request by job**
Fix error code 7 and add error code 8

https://www.iana.org/assignments/bgp-parameters/bgp-parameters.xhtml#bgp-parameters-3

### CODE REVIEW

**Comment by fxlb** [comment]
Thanks for this PR. Please, see CONTRIBUTING.md 7) Add/update tests.

**Comment by job** [comment]
@fxlb I am not able to provide tests for these changes. Reading the RFCs & the IANA registry it is obvious that the code for BGP Error code 7 is wrong, and Error code 8 should be considered trivial.

**Comment by fxlb** [comment]
Commit messages updated, merged, thanks.

**Comment by fxlb** [comment]
FYI, It better to not use the `master` branch for a PR.

**Pull request merged**
