### PR TITLE
Parse lower 4 bits in version field as hw info for arista ethertype

### PR DESCRIPTION
**Pull request by BrynXu**
This change is based on PR668, quote its comment first to understand this change easier:

"Arista applied for, and received the assignment of, a vendor-specific EtherType Protocol Identifier in May of 2016. Details below:
Ethertype number is: D28B
Issue date is: May 12, 2016

Arista Subtype 0x01 is Timestamp L2 Header
The timestamp L2 header consist of the following fields:
Arista EtherType (0xD28B)
Two-byte protocol subtype of 0x1
Two-byte protocol version: 0x10 for 64-bit timestamp and 0x20 for 48-bit timestamp"

Recently, Arista divides the two-byte protocol version field further into two fields:
One-byte protocol version: 0x1 for 64-bit timestamp and 0x2 for 48-bit timestamp
One-byte protocol hw version: 0x0 for not-specified, 0x1 for J2

With this new definition, the current dissector will fail to print timestamp correctly, this PR fixes the problem.

The output of tcpdump are like those:

13:36:40.091512 ethertype Arista Vendor Specific Protocol (0xd28b), length 110: SubType: 0x1, Version: 0x0010, Timestamp TAI(64-bit): 2019-05-29 20:36:39, 944724424 ns, IP 10.136.1.32 > 10.2.23.24:  ip-proto-63 62
13:36:40.579036 ethertype Arista Vendor Specific Protocol (0xd28b), length 110: SubType: 0x1, Version: 0x0011, Timestamp TAI(64-bit): 2019-05-29 20:36:40, 432245804 ns, IP 10.136.1.32 > 10.2.23.24:  ip-proto-63 58

13:37:41.551225 ethertype Arista Vendor Specific Protocol (0xd28b), length 108: SubType: 0x1, Version: 0x0020, Timestamp TAI(48-bit): Seconds 60821, Nanoseconds 404038772, IP 10.136.1.32 > 10.2.23.24:  ip-proto-63 62
13:37:42.040995 ethertype Arista Vendor Specific Protocol (0xd28b), length 108: SubType: 0x1, Version: 0x0021, Timestamp TAI(48-bit): Seconds 60821, Nanoseconds 893796872, IP 10.136.1.32 > 10.2.23.24:  ip-proto-63 58

### CODE REVIEW

**Comment by infrastation** [comment]
Thank you for preparing these changes. Please note that the new test cases would need to be in `tests/TESTLIST` to work, also that the code uses C99, so existing comments use an OK style. Is there any documentation for this EtherType?

**Comment by BrynXu** [comment]
> Thank you for preparing these changes. Please note that the new test cases would need to be in `tests/TESTLIST` to work, also that the code uses C99, so existing comments use an OK style. Is there any documentation for this EtherType?

Thanks for reviewing it. I update the existing test case's input pcap and output files to cover the change, so there is no new testcase added.
The change is documented in [Arista EOS Website](https://eos.arista.com/eos-4-26-2f/tap-aggregation-packet-timestamp/#Versions_Supported_for_L2_Header_Timestamping_Subtype), it is a public website but requires user registration.

**Comment by infrastation** [comment]
You are right, this updates existing tests only so `TESTLIST` does not need to be updated. On this note, the change modifies `arista_ether.pcap` as well, is it because the wire encoding has changed?

I have created an account at the portal, but apparently I am not authorized to view this particular document. @fenner, would it make more sense to put the current Arista packet diagrams into `print-arista.c`?

**Comment by fenner** [comment]
Would packet diagrams like this be enough?

```
The Arista timestamp header consists of the following fields:
1. The Arista ethertype (0xd28b)
2. A 2-byte subtype field; 0x01 indicates the timestamp header
3. A 2-byte version field, described below.
4. A 48-bit or 64-bit timestamp field, depending on the contents of the version field

This header is then followed by the original ethertype and the remainder of the original packet.

 0                   1                   2                   3  
 0 1 2 3 4 5 6 7 8 9 0 1 2 3 4 5 6 7 8 9 0 1 2 3 4 5 6 7 8 9 0 1
+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+
|                            dst mac                            |
+                               +-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+
|                               |                               |
+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+                               +
|                            src mac                            |
+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+
|        ethertype 0xd28b       |          subtype 0x1          |
+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+
|            version            |                               |
+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+                               +
|                          timestamp...                         |
+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+

The two-byte version value is split into 3 fields:
1. The timescale in use.  Currently assigned values include:
    0 = TAI
    1 = UTC
2. The timestamp format and length.  Currently assigned values include:
    1 = 64-bit timestamp
    2 = 48-bit timestamp
3. The hardware info
    0 = R/R2 series
    1 = R3 series

 0                   1          
 0 1 2 3 4 5 6 7 8 9 0 1 2 3 4 5
+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+
|   timescale   | format|hw info|
+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+
```

**Comment by infrastation** [comment]
Thank you, I expect to have another look in a few days.

**Comment by infrastation** [comment]
After looking at `print-arista.c` for a while I prepared a more substantial change, which is going to be committed tomorrow.

**Comment by infrastation** [comment]
Commit a807516 improves the associated code and adds support for HwInfo. Thank you @BrynXu for raising this issue and thank you @fenner for providing the packet diagram. Closing as resolved.

**Comment by fenner** [comment]
Thank you, @infrastation , for the extra improvements here!

**Pull request closed without merging**
