### PR TITLE
Seeing what it takes to get stuff tested with Travis/AppVeyor.

### PR DESCRIPTION
**Pull request by guyharris**
Ignore this, I'm just seeing whether this is sufficient to run this through Travis and AppVeyor, so I know how to update the CONTRIBUTING file.

### CODE REVIEW

**Comment by infrastation** [comment]
Both Travis CI and Appveyor checks now work, closing.

**Comment by gvanem** [comment]
> Both Travis CI and Appveyor checks now work, closing.

From the project front-page it's evident that Travis is passing, but not AppVeyor. Can you/Guy please add a link for that? Should AFAICS, be something like:
```diff
--- a/README.md 2018-06-05 11:06:43
+++ b/README.md 2018-08-01 08:49:40
@@ -3,6 +3,8 @@
 [![Build
 Status](https://travis-ci.org/the-tcpdump-group/tcpdump.png)](https://travis-ci.org/the-tcpdump-group/tcpdump)

+[![Build Status](https://ci.appveyor.com/api/projects/status/github/guyharris/tcpdump?branch=master)](https://ci.appveyor.com/project/guyharris/tcpdump)
+
 To report a security issue please send an e-mail to security@tcpdump.org.
```

**Comment by infrastation** [comment]
The Appveyor status image says "building..." despite the build finished successfully hours ago, do you get different result?

**Comment by infrastation** [comment]
Figured it out: the URL needs to be different for the image. Making the changes...

**Comment by infrastation** [comment]
Done in `README.md`, also on the web-site front page.

**Comment by infrastation** [comment]
If you do not want the result to be unreadable in a text console, I would suggest to remove both badges, because CI instances come and go, and README is better suited for less volatile information -- it usually comes in a package and then sits on the filesystem for months if not years. The web-site is a good place for the current up-to-date list.

**Pull request closed without merging**
