### PR TITLE
Initial support to parse QUIC packets.

### PR DESCRIPTION
**Pull request by rpaulo**
This is the initial support for parsing QUIC packets.  I'd like to get feedback from the community as to the code readiness of this diff.  I'm aware the unit tests are missing, but I will correct that once the code is accepted.

This is how the parser looks like right now.
```
tcpdump: listening on lo0, link-type NULL (BSD loopback), snapshot length 524288 bytes
18:56:36.488940 IP6 (flowlabel 0x50500, hlim 64, next-header UDP (17) payload length: 1208) ::1.60794 > ::1.443: quic, initial, dcid f9f4b0816e432d29, length 1182
18:56:36.500845 IP6 (flowlabel 0xb0900, hlim 64, next-header UDP (17) payload length: 142) ::1.443 > ::1.60794: quic, initial, scid efa67422ee5c3eb0, length 116
18:56:36.500871 IP6 (class 0x02, flowlabel 0xb0900, hlim 64, next-header UDP (17) payload length: 1205) ::1.443 > ::1.60794: quic, handshake, scid efa67422ee5c3eb0, length 1180
18:56:36.500881 IP6 (class 0x02, flowlabel 0xb0900, hlim 64, next-header UDP (17) payload length: 127) ::1.443 > ::1.60794: quic, handshake, scid efa67422ee5c3eb0, length 102
18:56:36.509651 IP6 (flowlabel 0x50500, hlim 64, next-header UDP (17) payload length: 1208) ::1.60794 > ::1.443: quic, initial, dcid efa67422ee5c3eb0, length 1182
18:56:36.509731 IP6 (class 0x02, flowlabel 0x50500, hlim 64, next-header UDP (17) payload length: 47) ::1.60794 > ::1.443: quic, handshake, dcid efa67422ee5c3eb0, length 22
18:56:36.510251 IP6 (class 0x02, flowlabel 0x50500, hlim 64, next-header UDP (17) payload length: 81) ::1.60794 > ::1.443: quic, handshake, dcid efa67422ee5c3eb0, length 56
18:56:36.510618 IP6 (class 0x02, flowlabel 0xb0900, hlim 64, next-header UDP (17) payload length: 50) ::1.443 > ::1.60794: quic, handshake, scid efa67422ee5c3eb0, length 25
18:56:36.510715 IP6 (class 0x02, flowlabel 0xb0900, hlim 64, next-header UDP (17) payload length: 29) ::1.443 > ::1.60794: quic, protected
18:56:36.510883 IP6 (class 0x02, flowlabel 0xb0900, hlim 64, next-header UDP (17) payload length: 250) ::1.443 > ::1.60794: quic, protected
18:56:36.511289 IP6 (class 0x02, flowlabel 0x50500, hlim 64, next-header UDP (17) payload length: 39) ::1.60794 > ::1.443: quic, protected, dcid efa67422ee5c3eb0
18:56:36.511551 IP6 (class 0x02, flowlabel 0x50500, hlim 64, next-header UDP (17) payload length: 37) ::1.60794 > ::1.443: quic, protected, dcid efa67422ee5c3eb0
18:56:36.511655 IP6 (class 0x02, flowlabel 0x50500, hlim 64, next-header UDP (17) payload length: 37) ::1.60794 > ::1.443: quic, protected, dcid efa67422ee5c3eb0
18:56:36.511692 IP6 (class 0x02, flowlabel 0xb0900, hlim 64, next-header UDP (17) payload length: 34) ::1.443 > ::1.60794: quic, protected
18:56:36.511762 IP6 (class 0x02, flowlabel 0x50500, hlim 64, next-header UDP (17) payload length: 44) ::1.60794 > ::1.443: quic, protected, dcid efa67422ee5c3eb0
18:56:36.512221 IP6 (class 0x02, flowlabel 0xb0900, hlim 64, next-header UDP (17) payload length: 86) ::1.443 > ::1.60794: quic, protected
18:56:36.512285 IP6 (class 0x02, flowlabel 0xb0900, hlim 64, next-header UDP (17) payload length: 29) ::1.443 > ::1.60794: quic, protected
18:56:36.512619 IP6 (class 0x02, flowlabel 0x50500, hlim 64, next-header UDP (17) payload length: 39) ::1.60794 > ::1.443: quic, protected, dcid efa67422ee5c3eb0
```

### CODE REVIEW

**Comment by rpaulo** [comment]
Looks like I forgot to add the file to cmake in addition to using the right format string.  Will fix it, but feel free to comment on the other parts of the code in the mean time.

**Review by mcr — APPROVED** [review]
Yes, we'd like some test packets please.
Your use of GET_ macros seems correct to me.

**Comment by fxlb** [comment]
Thanks for the update. Before a merge please 
1. remove trailing spaces/tabs,
2. rebase on top of  the-tcpdump-group:master and rebase -i to have only one commit.

**Comment by rpaulo** [comment]
> Thanks for the update. Before a merge please
> 
> 1. remove trailing spaces/tabs,
> 2. rebase on top of  the-tcpdump-group:master and rebase -i to have only one commit.

Done!

**Comment by fxlb** [comment]
Removed trailing tabs on line 85.

**Comment by fxlb** [comment]
Missed warnings in Windows builds (32 bits):
```
C:\projects\tcpdump\print-quic.c(110): warning C4028: formal parameter 3 different from declaration [C:\projects\tcpdump\build\netdissect.vcxproj]
C:\projects\tcpdump\print-quic.c(133): warning C4244: '=': conversion from 'uint64_t' to 'uint8_t', possible loss of data [C:\projects\tcpdump\build\netdissect.vcxproj]
C:\projects\tcpdump\print-quic.c(220): warning C4242: 'function': conversion from 'uint64_t' to 'std::size_t', possible loss of data [C:\projects\tcpdump\build\netdissect.vcxproj]
C:\projects\tcpdump\print-quic.c(221): warning C4242: 'function': conversion from 'uint64_t' to 'std::size_t', possible loss of data [C:\projects\tcpdump\build\netdissect.vcxproj]
C:\projects\tcpdump\print-quic.c(224): warning C4242: 'function': conversion from 'uint64_t' to 'std::size_t', possible loss of data [C:\projects\tcpdump\build\netdissect.vcxproj]
C:\projects\tcpdump\print-quic.c(231): warning C4242: 'function': conversion from 'uint64_t' to 'std::size_t', possible loss of data [C:\projects\tcpdump\build\netdissect.vcxproj]
C:\projects\tcpdump\print-quic.c(232): warning C4242: 'function': conversion from 'uint64_t' to 'std::size_t', possible loss of data [C:\projects\tcpdump\build\netdissect.vcxproj]
C:\projects\tcpdump\print-quic.c(234): warning C4242: 'function': conversion from 'uint64_t' to 'std::size_t', possible loss of data [C:\projects\tcpdump\build\netdissect.vcxproj]
C:\projects\tcpdump\print-quic.c(274): warning C4028: formal parameter 3 different from declaration [C:\projects\tcpdump\build\netdissect.vcxproj]
```
https://ci.appveyor.com/project/guyharris/tcpdump/builds/41365352/job/mrddy4viik4omnmp

**Comment by gvanem** [comment]
> ... `'std::size_t',` ...

Looks like a C++ warning. Yet option `/TC` was used. WTF!?

**Comment by fxlb** [comment]
With Visual Studio 16 2019:
```
C:\projects\tcpdump\print-quic.c(220,41): warning C4242: 'function': conversion from 'uint64_t' to 'size_t', possible loss of data [C:\projects\tcpdump\build\netdissect.vcxproj]
```
Thus, no 'std::size_t' with this compiler...

**Comment by guyharris** [comment]
> Thus, no `'std::size_t'` with this compiler...

If, by that, you mean "no 64-bit `size_t` with this compiler", that's true. (`std::` is a C++-ism, and this is presumably C code, so that doesn't apply.)

It's true because it's a 32-bit build, so `size_t` should be 32-bit, and a warning *should* be issued for an assignment of `uint64_t` to `size_t`.

And the correct fix may simply be to introduce a cast, e.g.

    prefix = (uint8_t)v >> 6;

in `get_be_vli()` - `v` is 64-bit because it's used to construct a 64-bit value, but, at *that* point, it's been set by a call to `GET_U_1()`, so it's known to be in the range 0-255 and thus to fit into a `uint8_t`.

An alternative would be something such as

```
static inline uint64_t
get_be_vli(netdissect_options *ndo, const u_char *p, uint8_t *out_length)
{
	uint64_t v;
	uint8_t first_octet;
	uint8_t prefix;
	uint8_t length;

	first_octet = GET_U_1(p);
	p++;
	prefix = first_octet >> 6;
	length = 1 << prefix;
	if (out_length != NULL)
		*out_length = length;
	v = first_octet & 0x3f;
	while (length > 1) {
		v = (v << 8) + GET_U_1(p);
		p++;
		length--;
	}
 	return v;
}
```

**Comment by rpaulo** [comment]
> Missed warnings in Windows builds (32 bits):
> 
> ```
> C:\projects\tcpdump\print-quic.c(110): warning C4028: formal parameter 3 different from declaration [C:\projects\tcpdump\build\netdissect.vcxproj]
> C:\projects\tcpdump\print-quic.c(133): warning C4244: '=': conversion from 'uint64_t' to 'uint8_t', possible loss of data [C:\projects\tcpdump\build\netdissect.vcxproj]
> C:\projects\tcpdump\print-quic.c(220): warning C4242: 'function': conversion from 'uint64_t' to 'std::size_t', possible loss of data [C:\projects\tcpdump\build\netdissect.vcxproj]
> C:\projects\tcpdump\print-quic.c(221): warning C4242: 'function': conversion from 'uint64_t' to 'std::size_t', possible loss of data [C:\projects\tcpdump\build\netdissect.vcxproj]
> C:\projects\tcpdump\print-quic.c(224): warning C4242: 'function': conversion from 'uint64_t' to 'std::size_t', possible loss of data [C:\projects\tcpdump\build\netdissect.vcxproj]
> C:\projects\tcpdump\print-quic.c(231): warning C4242: 'function': conversion from 'uint64_t' to 'std::size_t', possible loss of data [C:\projects\tcpdump\build\netdissect.vcxproj]
> C:\projects\tcpdump\print-quic.c(232): warning C4242: 'function': conversion from 'uint64_t' to 'std::size_t', possible loss of data [C:\projects\tcpdump\build\netdissect.vcxproj]
> C:\projects\tcpdump\print-quic.c(234): warning C4242: 'function': conversion from 'uint64_t' to 'std::size_t', possible loss of data [C:\projects\tcpdump\build\netdissect.vcxproj]
> C:\projects\tcpdump\print-quic.c(274): warning C4028: formal parameter 3 different from declaration [C:\projects\tcpdump\build\netdissect.vcxproj]
> ```
> 
> https://ci.appveyor.com/project/guyharris/tcpdump/builds/41365352/job/mrddy4viik4omnmp

Fixed.  Is this ready to go in now?

**Comment by fxlb** [comment]
>Fixed. Is this ready to go in now?

Yes. thank you!

**Comment by gvanem** [comment]
I note for all `tests/quic*.pcap` files, tcpdump gives bad UDP checksums.
E.g.  `windump.exe -tnr tests/quic_handshake.pcap -vv` says:
`[bad udp cksum 0x04cb -> 0x88c5!]` for the first frame.

But with `tshark -Vnr tests/quic_handshake.pcap` it says:
```
User Datagram Protocol, Src Port: 50606, Dst Port: 443
    Source Port: 50606
    Destination Port: 443
    Length: 1208
    Checksum: 0x04cb [unverified]
```
for the first frame. Not sure what  `[unverified]` means here. or which program is most precise.

**Comment by fxlb** [comment]
With `tshark -o  udp.check_checksum:TRUE -V -r tests/quic_handshake.pcap`, we have:
```
    Checksum: 0x04cb incorrect, should be 0x88c5 (maybe caused by "UDP checksum offload"?)
        [Expert Info (Error/Checksum): Bad checksum [should be 0x88c5]]
            [Bad checksum [should be 0x88c5]]
            [Severity level: Error]
            [Group: Checksum]
        [Calculated Checksum: 0x88c5]
    [Checksum Status: Bad]
```

**Comment by fxlb** [comment]
There is a new defect reported by the tool Coverity Scan:
*** CID 1493488:  Control flow issues  (DEADCODE)
/print-quic.c: 179 in quic_print_packet()

coverity-scan-quic1
)

**Comment by fxlb** [comment]
`packet_type = (first_octet >> 4) & 0x02;`
Should be
`packet_type = (first_octet >> 4) & 0x03;`
?

**Comment by rpaulo** [comment]
> `packet_type = (first_octet >> 4) & 0x02;`
> Should be
> `packet_type = (first_octet >> 4) & 0x03;`
> ?

Yes my bad. I should have added a test for retry packets

**Comment by fxlb** [comment]
Have you a pcap file with retry packets?

**Comment by rpaulo** [comment]
> Do you have a pcap file with retry packets?

Yes, will send a new PR shortly.

**Pull request merged**
