### PR TITLE
Initial support for the REdis Serialization Protocol known as RESP.

### PR DESCRIPTION
**Pull request by adarqui**
This commit adds support for RESP as defined in: http://redis.io/topics/protocol.
It also supports inline commands and pipelining. Due to the popularity of RESP,
numerous services are emerging that use this protocol. You may decode RESP packets
on arbitrary ports using the "-T redis" option.

Example captures can be found in tests/resp*.

A simple way to test this parser is to start redis-server and then run
redis-cli commands such as "redis-cli set key value".

Traditionally, redis-cli monitor is used to debug redis. Unfortunately,
the "monitor" command can cause significant load on a redis-server in
production. This parser may be used as a non-invasive alternative to
redis-cli monitor.

### CODE REVIEW

**Comment by adarqui** [comment]
@mcr  , @infrastation  , @fxlb ,

Here's the PR with the fixed copyright header.

**Comment by infrastation** [comment]
I have studied the RESP encoding specification but not the new source code yet.

**Comment by adarqui** [comment]
Hey @infrastation, @mcr, @fxlb,

Wondering if you guys have tried the redis/resp mods out? Or if you have any questions about the PR? I'd like to eventually writer parsers for AMQP & STOMP. But, i'd like to get this PR accepted (if it's good enough) first before I attempt to take those on. Let me know if you need anything.

Thanks!

**Comment by infrastation** [comment]
Other things keep getting in the way.

**Comment by fxlb** [comment]
@adarqui Sorry for this late review.
Some comments after a first review:
1. There is a need for a rebase on the current master branch and some changes as a result of commits 99c91c3 and c1c3c77.
2. There are some warnings given by `touch .devel; ./configure; make clean all` for print-redis.c. Could you review?
(More informations in 4) in the new CONTRIBUTING file)
4. TESTRLVOID macro is not used. It should be removed.
5. TESTRLVOID_NORETURN is only used once. It would be more clear to delete it and to put the code of replacement directly.
6. Line 347: print 'invalid' and not tstr[] string for a trucated case. Why?
7. There is a mixing of 'resp' and 'redis' names. RESP is a protocol, not Redis. It would be thus preferable to use 'resp'/'RESP' names in the codes and file names instead of 'redis'/'REDIS'. (mv print-redis.c print-resp.c ; s/redis_/resp_/ ; s/REDIS_RESP_/RESP_/ ; s/PT_REDIS/PT_RESP/ ; REDIS_PORT... ; "redis"... ;  etc.).
8. There is a loop problem found by fuzzing. You will see it with the following pcap file (encoded with xxd):
Put hexdump in a 'resp-long-loop.pcap.xxd' file
xxd -r resp-long-loop.pcap.xxd resp-long-loop.pcap
./tcpdump -T resp -r resp-long-loop.pcap

```
0000000: 0a0d 0d0a 3400 0000 4d3c 2b1a 0100 0000  ....4...M<+.....
0000010: ffff ffff ffff ffff 0400 0f00 4564 6974  ............Edit
0000020: 6361 7020 312e 3939 2e31 3000 0000 0000  cap 1.99.10.....
0000030: 3400 0000 0100 0000 2000 0000 0100 0000  4....... .......
0000040: 0000 0400 0900 0100 0600 0000 0000 0000  ................
0000050: 2000 0000 0600 0000 bc05 0000 0000 0000   ...............
0000060: b581 0400 0e3a bfc8 9a05 0000 9a05 0000  .....:..........
0000070: 0008 027e b2b6 0021 d801 0345 0800 4500  ...~...!...E..E.
0000080: 058c 563d 4000 8006 9d3b 0a02 372b c0a8  ..V=@....;..7+..
0000090: 0092 0050 04e6 0f5f 119c e297 da4a 5010  ...P..._.....JP.
00000a0: fe2a 4a11 0000 2430 8204 6030 8203 4ca0  .*J...$0..`0..L.
00000b0: 0302 0102 020a 2eab 11dc 50ff 5c9d ebc0  ..........P.\...
00000c0: 3009 0605 2b25 0079 1d05 0030 7031 2b30  0...+%.y...0p1+0
00000d0: 2907 0355 040b 1322 436f 7079 7269 6768  )..U..."Copyrigh
00000e0: 7420 2863 2920 4e39 3937 204d 6963 726f  t (c) N997 Micro
00000f0: 336f 6674 2043 6f72 702e 311e 301c 0603  3oft Corp.1.0...
0000100: 5504 0b13 154d 6963 726f 7325 0074 2043  U....Micros%.t C
0000110: 6f72 706f 7261 7469 6f6e 3121 301f 0603  orporation1!0...
0000120: 5504 0513 184d 6963 726f 736f 6674 2052  U....Microsoft R
0000130: 516f 7420 4175 7468 6f72 6974 7930 1e17  Qot Authority0..
0000140: 0d2a 3730 3832 3232 3233 3130 325a 1725  .*70822223102Z.%
0000150: 0032 3038 3235 b037 3030 3030 5a30 7931  .20825.70000Z0y1
0000160: 0b30 0906 2500 0406 1302 5553 3113 3011  .0..%.....US1.0.
0000170: 0640 5504 0813 0a57 6173 6869 6e67 4b6f  .@U....WashingKo
0000180: 6e31 1030 0e06 0355 0407 1307 5265 646d  n1.0...U....Redm
0000190: 6f6e 6431 1e30 1c06 0365 040a 1315 4d69  ond1.0...e....Mi
00001a0: 6372 6f73 6f79 7420 436f 4a70 6f72 6174  crosoyt CoJporat
00001b0: 696f 6e35 2330 2106 0355 0403 131a 4d69  ion5#0!..U....Mi
00001c0: 6372 6f73 6f66 7420 436f 6465 2053 6967  crosoft Code Sig
00001d0: 6e69 6ef5 2040 4341 3082 0122 300d 0609  nin. @CA0.."0...
00001e0: 2a86 4886 f70d 0101 0105 0003 8201 0f46  *.H............F
00001f0: 3082 010a 0282 0101 024f 797d d65d b345  0........Oy}.].E
0000200: 39a8 34ac 31d8 f925 3549 77c0 fb1f 9ec7  9.4.1..%5Iw.....
0000210: 4571 efd1 46e8 d48c 2067 4c52 62f4 9902  Eq..F... gLRb...
0000220: c34d d849 6c2f 243e 65aa aaaa aaaa aaaa  .M.Il/$>e.......
0000230: aaaa aaaa aaaa aaaa aaaa aaaa aaaa aaaa  ................
0000240: aaaa aaaa aaaa aaaa aaaa aaaa aaaa aaaa  ................
0000250: aaaa aaaa aaaa aaaa aaaa aaaa aaaa aaaa  ................
0000260: aaaa aaaa aaaa aaaa aaaa aaaa aaaa aaaa  ................
0000270: aaaa aaaa aaaa aaaa aaaa aaaa aaaa aaaa  ................
0000280: aaaa aaaa aaaa aaaa aaaa aaaa aaaa aaaa  ................
0000290: aaaa aaaa aaaa aaaa aaaa aaaa aaaa aaaa  ................
00002a0: aaaa aaaa aaaa aaaa aaaa aaaa aaaa aaaa  ................
00002b0: aaaa aaaa aaaa aaaa aaaa aaaa aaaa aaaa  ................
00002c0: aaaa aaaa aaaa aaaa aaaa aaaa aaaa aaaa  ................
00002d0: aaaa aaaa aaaa aaaa aaaa aaaa aaaa aaaa  ................
00002e0: aaaa aaaa aaaa aaaa aaaa aaaa aaaa aaaa  ................
00002f0: aaaa aaaa aaaa aaaa aaaa aaaa aaaa aaaa  ................
0000300: aaaa aaaa aaaa aaaa aaaa aaaa aaaa aaaa  ................
0000310: aaaa aaaa aaaa aaaa aaaa aaaa aaaa aaaa  ................
0000320: aaaa aaaa aaaa aaaa aaaa aaaa aaaa aaaa  ................
0000330: aaaa aaaa aaaa aaaa aaaa aaaa aaaa aaaa  ................
0000340: aaaa aaaa aaaa aaaa aaaa aaaa aaaa aaaa  ................
0000350: aaaa aaaa aaaa aaaa aaaa aaaa aaaa aaaa  ................
0000360: aaaa aaaa aaaa aaaa aaaa aaaa aaaa aaaa  ................
0000370: aaaa aaaa aaaa aaaa aaaa aaaa aaaa aaaa  ................
0000380: aaaa aaaa aaaa aaaa aaaa aaaa aaaa aaaa  ................
0000390: aaaa aaaa aaaa aaaa aaaa aaaa aaaa aaaa  ................
00003a0: aaaa aaaa aaaa aaaa aaaa aaaa aaaa aaaa  ................
00003b0: aaaa aaaa aaaa aaaa aaaa aaaa aaaa aaaa  ................
00003c0: aaaa aaaa aaaa aaaa aaaa aaaa aaaa aaaa  ................
00003d0: aaaa aaaa aaaa aaaa aaaa aaaa aaaa aaaa  ................
00003e0: aaaa aaaa aaaa aaaa aaaa aaaa aaaa aaaa  ................
00003f0: aaaa aaaa aaaa aaaa aaaa aaaa aaaa aaaa  ................
0000400: aaaa aaaa aaaa aaaa aaaa aaaa aaaa aaaa  ................
0000410: aaaa aaaa aaaa aaaa aaaa aaaa aaaa aaaa  ................
0000420: aaaa aaaa aaaa aaaa aaaa aaaa aaaa aaaa  ................
0000430: aaaa aaaa aaaa aaaa aaaa aaaa aaaa aaaa  ................
0000440: aaaa aaaa aaaa aaaa aaaa aaaa aaaa aaaa  ................
0000450: aaaa aaaa aaaa aaaa aaaa aaaa aaaa aaaa  ................
0000460: aaaa aaaa aaaa aaaa aaaa aaaa aaaa aaaa  ................
0000470: aaaa aaaa aaaa aaaa aaaa aaaa aaaa aaaa  ................
0000480: aaaa aaaa aaaa aaaa aaaa aaaa aaaa aaaa  ................
0000490: aaaa aaaa aaaa aaaa aaaa aaaa aaaa aaaa  ................
00004a0: aaaa aaaa aaaa aaaa aaaa aaaa aaaa aaaa  ................
00004b0: aaaa aaaa aaaa aaaa aaaa aaaa aaaa aaaa  ................
00004c0: aaaa aaaa aaaa aaaa aaaa aaaa aaaa aaaa  ................
00004d0: aaaa aaaa aaaa aaaa aaaa aaaa aaaa aaaa  ................
00004e0: aaaa aaaa aaaa aaaa aaaa aaaa aaaa aaaa  ................
00004f0: aaaa aaaa aaaa aaaa aaaa aaaa aaaa aaaa  ................
0000500: aaaa aaaa aaaa aaaa aaaa aaaa aaaa aaaa  ................
0000510: aaaa aaaa aaaa aaaa aaaa aaaa aaaa aaaa  ................
0000520: aaaa aaaa aaaa aaaa aaaa aaaa aaaa aaaa  ................
0000530: aaaa aaaa aaaa aaaa aaaa aaaa aaaa aaaa  ................
0000540: aaaa aaaa aaaa aaaa aaaa aaaa aaaa aaaa  ................
0000550: aaaa aaaa aaaa aaaa aaaa aaaa aaaa aaaa  ................
0000560: aaaa aaaa aaaa aaaa aaaa aaaa aaaa aaaa  ................
0000570: aaaa aaaa aaaa aaaa aaaa aaaa aaaa aaaa  ................
0000580: aaaa aaaa aaaa aaaa aaaa aaaa aaaa aaaa  ................
0000590: aaaa aaaa aaaa aaaa aaaa aaaa aaaa aaaa  ................
00005a0: aaaa aaaa aaaa aaaa aaaa aaaa aaaa aaaa  ................
00005b0: aaaa aaaa aaaa aaaa aaaa aaaa aaaa aaaa  ................
00005c0: aaaa aaaa aaaa aaaa aaaa aaaa aaaa aaaa  ................
00005d0: aaaa aaaa aaaa aaaa aaaa aaaa aaaa aaaa  ................
00005e0: aaaa aaaa aaaa aaaa aaaa aaaa aaaa aaaa  ................
00005f0: aaaa aaaa aaaa aaaa aaaa aaaa aaaa aaaa  ................
0000600: aaaa aaaa aaaa aaaa aaaa 0000 bc05 0000  ................
```

**Comment by adarqui** [comment]
Thanks so much fxlb, for the valuable feedback. Much appreciated. Hopefully I can look at all of this during the weekend.

**Comment by infrastation** [comment]
Also please check commit 3fb4560.

**Comment by fxlb** [comment]
Another problem to fix: the `%.*s` format don't filter the non-printable characters. There is a need to use one of `fn_printX` function (see: `util-print.c`).

**Comment by adarqui** [comment]
Hey fxlb,

I made a new branch to test out my modifications etc. Do you want me to temporarily create another pull request? It's not something that would be pulled in (even if it's 100% correct) because the commit history isn't up to par with the CONTRIBUTING file; I have several commits. Here's the branch:

https://github.com/adarqui/tcpdump/tree/resp-dev

I rebased, renamed functions/files, made several modifications (fn_print etc) & everything is working, including the fix which prevents that loop you found in fuzzing.

As for the "invalid" versus printing tstr; are you referring to the one on line 350? If so, I could remove that call to resp_print_invalid() and just print tstr to indicate we truncated the output.

Thanks!

**Comment by fxlb** [comment]
Thank you, I will review in a few days.

**Comment by fxlb** [comment]
Hello @adarqui,
Thanks, many fixes were done. Some comments after a review of the new code:

1. In netdissect.h, need to fix indent.
2. In print-tcp.c & tcp.h, s/REDIS_PORT/RESP_PORT/.
3. In print-resp.c, remove `#include "interface.h"` (no more needed).
4. In print-resp.c, s/REDIS_RESP_/RESP_/.
5. In print-resp.c, line 149, 331 & 332, redis/Redis in comments, maybe RESP?
6. In print-resp.c, line 221 & 252, need fn_printX() to filter the non-printable characters, like the update done in resp_print_inline().
7. In print-resp.c, line 350, is it invalid or just truncated?

Could you update?

**Comment by adarqui** [comment]
Hey fxlb,

I mentioned in my previous comment that I put it in the resp-dev branch. So I think you looked at the older code :/ Sorry if I wasn't clear. I addressed all of the things you mentioned in the "resp-dev" branch. I didn't merge it into master because I have several commits etc.

Do you think I should create a new pull request with the resp-dev branch? I think that would be good, it would probably have prevented the confusion.

Sorry again.

Thanks

**Comment by fxlb** [comment]
I look at your branch:
```
commit a7e87610b1b50a9d0ebb3439aa5de51bdd730d11
Author: Andrew Darqui <andrew.darqui@gmail.com>
Date:   Fri Jan 15 15:31:46 2016 -0500

    wording

commit cb33775342274a49fe0d66137481b62e33f087eb
Author: Andrew Darqui <andrew.darqui@gmail.com>
Date:   Fri Jan 15 15:21:55 2016 -0500

    use fn_printn to avoid printing non-printable chars

commit 4267611ea21cc2979009abb32a3dfff4f41954fc
Author: Andrew Darqui <andrew.darqui@gmail.com>
Date:   Fri Jan 15 15:07:20 2016 -0500

    getting rid of register

commit 34183631c0fff3b323c070311ecdf63344ba2381
Author: Andrew Darqui <andrew.darqui@gmail.com>
Date:   Fri Jan 15 13:43:00 2016 -0500

    testing resp code with the new changes

commit 71b3f069a5f82e5e2abf4ad6c103d296029155f8
Author: Andrew Darqui <andrew.darqui@gmail.com>
Date:   Tue Jan 12 12:33:25 2016 -0500

    print-redis.c

commit 891ed135354bb9c41209b8a3b47643a283680ff9
Author: Andrew Darqui <andrew.darqui@gmail.com>
Date:   Tue Jan 12 12:32:55 2016 -0500

    RESP
```

**Comment by adarqui** [comment]
Oh ok sorry, my mistake! Thanks alot. I will probably make those updates in the next few hours & reply.

As for the REDIS_PORT vs RESP_PORT; don't you think REDIS_PORT would be more acceptable? Everything else should be RESP_ like you said, but for the port I would think REDIS_PORT would make more sense.

Thanks fxlb!

**Comment by fxlb** [comment]
No problem.
For the REDIS_PORT vs RESP_PORT, the http://redis.io/topics/protocol says that the 6379 port is for REDIS, so I agree that REDIS_PORT is the good name.
Thanks.

**Comment by adarqui** [comment]
Hey fxlb,

I just pushed the requested changes to the resp-dev branch, except for these:

5. In print-resp.c, line 149, 331 & 332, redis/Redis in comments, maybe RESP?

I think we should leave it as "redis" because inlining and pipelining are supported by redis, which uses RESP. For example in the protocol spec: http://redis.io/topics/protocol

"Redis supports pipelining (covered later in this document). So it is possible for clients to send multiple commands at once, and wait for replies later."

"Sometimes you have only telnet in your hands and you need to send a command to the Redis server. While the Redis protocol is simple to implement it is not ideal to use in interactive sessions, and redis-cli may not always be available. For this reason Redis also accepts commands in a special way that is designed for humans, and is called the inline command format."

So that's why I didn't rename it to RESP; because for those specific functions which parse resp messages in a pipeline or inline, it's more specific to redis.


7. In print-resp.c, line 350, is it invalid or just truncated?

I kept that as "invalid" because if we are parsing these resp messages in a pipeline or inline, truncating could cause us to potentially miss valid (subsequent) resp messages in the pipeline. For example, I could send something such as:

```
$ printf -- "*-2\r\n*2\r\n\$4\r\nINCR\r\n\$1\r\nz\r\n*-3\r\n*2\r\n\$4\r\nINCR\r\n\$1\r\nz\r\n" | nc localhost 6379
```

The above command includes an invalid command (*-2\r\n), valid command (INCR z), invalid command (*-3\r\n), and another valid command (INCR z). Redis will disregard those invalid resp messages in the pipeline. It will also process both of those INCR's successfully. So the tcpdump output for that packet looks like this:

```
13:20:07.697297 IP 127.0.0.1.46435 > 127.0.0.1.6379: Flags [P.], seq 1:53, ack 1, win 342, options [nop,nop,TS val 1104682084 ecr 1104682084], length 52: RESP invalid "INCR" "z" invalid "INCR" "z"
```

Let me know what you think. Thanks alot!

**Comment by fxlb** [comment]
For first subject:
> So that's why I didn't rename it to RESP; because for those specific functions which parse resp messages in a pipeline or inline, it's more specific to redis.

Not sure I understand the subtle difference, but OK to let Redis in these comments.

**Comment by fxlb** [comment]
For the second subject:
I try your printf command In front of a redis-server and it show that the 'invalid' print is done in line 322 and not in line 356 (new for 350). Did I miss something?

**Comment by fxlb** [comment]
Is the '*' at the end of line 161 a typo?

**Comment by adarqui** [comment]
Hey fxlb,

> For the second subject:
> I try your printf command in front of a redis-server and it shows that the 'invalid' print is done in line 322 and not in line 356 (new for 350). Did I miss something?

I looked at the cases which generated that "invalid" message and it's definitely best to simply jump to trunc. It was only happening during an inline parse where no \r\n was found at the end of the string, which is invalid anyway. So I took that call out and instead it gets to trunc. Thanks!

I regenerated the resp_3_malicious.pcap and resp_3.out test cases. Those were generated from scripts that try to pass really big numbers, arrays, string sizes, etc to "overflow the parser". So those still pass as expected. The only thing that's missing in those new test cases is the "invalid" string, since we jump to trunc. That looks much better.


> Is the '*' at the end of line 161 a typo?

Yup thanks! fixed.


I pushed those commits up to resp-dev.

Thanks very much for the feedback/help. Let me know if you have any more feedback/concerns.

**Comment by fxlb** [comment]
Hello Andrew, thanks for the updates.

Sorry, I forgot to say that currently the printers use istr[] string (like invalid) to print " (invalid)". I just make an update to change istr[] to global, so no need for a printer to define it. Thus please rebase on master to use it.

> I looked at the cases which generated that "invalid" message and it's definitely best to simply jump to trunc. It was only happening during an inline parse where no \r\n was found at the end of the string, which is invalid anyway. So I took that call out and instead it gets to trunc.

To avoid any misunderstanding, I specify that 'trunc' (with the tstr[] message) is only for cases where we know that the packet was truncated (thus incomplete) via f.e. `-s snaplen` option of tcpdump, ND_TTEST* or ND_TCHECK* are ways to test the truncation. So for the truncated part, we can't say that the packet is invalid or not, we can only say 'trunc'. If we know that we are analysing a complete part (no truncation) of a packet, we can sometimes says that this part in invalid f.e. we expect \r\n and it's missing or we got only \n, etc.

Thus the questions: are the following tests trucation tests, can they use trunc label?
(I add ND_PRINT() for debug)
```
#define TEST_RET_LEN(rl) \
    if (rl < 0) { ND_PRINT((ndo, "X")); goto trunc; } else { return rl; }

#define TEST_RET_LEN_NORETURN(rl) \
    if (rl < 0) { ND_PRINT((ndo, "Y")); goto trunc; }
```
It seems not because if I use `printf -- "\r\n" | sudo nc localhost 6379`
I got `RESPXY [|RESP]` but this case is not a 'trunc' case, the packet is complete, but perhaps invalid.
Did I miss sometthing?

**Comment by adarqui** [comment]
Hey everyone,

I'm closing this PR. Sorry if I wasted anyone's time. I don't have the time to work on this at all, even though it seems (to me) like it's inches away from being acceptable.

@mcr , you asked me to fix this up.. Upon your request, I did (or tried). It's basically done. I'm donating this code to the-tcpdump-group. If you guys want to use it, awesome. If not, fine by me, bummer. Maybe we can pretend it's 1998 and I sent you guys a tcpdump-redis.diff patch, then I died. That shouldn't make the code worthless, unless the code itself is actually worthless.

FWIW, I use this code every day in production to dump redis packets; works great for me. Was just trying to help people who use tcpdump to dump redis packets.

Thanks again,

-- adarqui

**Comment by fxlb** [comment]
Hi @adarqui,
Thanks for your patience and your work.
I hope to have time in a few days to merge your code and fix the remaining problems, visible only if packets are invalid ones.
Thanks again.
fxlb

**Comment by adarqui** [comment]
@fxlb,

That is very great to hear! Thanks so much!

-- adarqui

**Comment by fxlb** [comment]
@adarqui Ready to merge.
For a better history, I suggest to fold all your commits into one, with a commit message like your first one. I can do that if you agree. Please, let me know.
```
Initial support for the REdis Serialization Protocol known as RESP.

This commit adds support for RESP as defined in: http://redis.io/topics/protocol.
It also supports inline commands and pipelining. Due to the popularity of RESP,
numerous services are emerging that use this protocol. You may decode RESP packets
on arbitrary ports using the "-T resp" option.

Example captures can be found in tests/resp_*.

A simple way to test this parser is to start redis-server and then run
redis-cli commands such as "redis-cli set key value".

Traditionally, redis-cli monitor is used to debug redis. Unfortunately,
the "monitor" command can cause significant load on a redis-server in
production. This parser may be used as a non-invasive alternative to
redis-cli monitor.
```

**Comment by adarqui** [comment]
Hey fxlb!

Nice! I folded the commits into one and uploaded it to yet another branch: resp-dev-squashed. Does that look correct? It looks good to me but you never know I could have missed something. Let me know.

Thanks alot

**Comment by fxlb** [comment]
Problem, on resp-dev-squashed branch, I got:
```
$ git diff --name-only resp-dev
print-resp.c
tests/resp_3.out
tests/resp_3_malicious.pcap
```
```patch
diff --git a/print-resp.c b/print-resp.c
index 6f28105..566de65 100644
--- a/print-resp.c
+++ b/print-resp.c
@@ -85,7 +85,7 @@ static int resp_print_inline(netdissect_options *, register const u_char *, int)
  * If we exceed, jump to trunc.
  */
 #define MOVE_FORWARD_CR_OR_LF(ptr, len) \
-    while(*ptr != '\r' && *ptr != '\n') { ND_TCHECK(*ptr); ptr++; len--; }
+    while(*ptr != '\r' && *ptr != '\n') { ND_TCHECK(*ptr);  ptr++; len--; }
 
 /*
  * CONSUME_CR_OR_LF
@@ -353,5 +353,6 @@ resp_print_inline(netdissect_options *ndo, register const u_char *bp, int length
     TEST_RET_LEN(length - length_cur);
 
 trunc:
+    resp_print_invalid(ndo);
     return (-1);
 }
diff --git a/tests/resp_3.out b/tests/resp_3.out
index eb9d8a9..b02f731 100644
--- a/tests/resp_3.out
+++ b/tests/resp_3.out
@@ -1,163 +1,168 @@
-IP 127.0.0.1.52759 > 127.0.0.1.6379: Flags [F.], seq 2169831382, ack 489972337, win 342, options [nop,nop,TS val 1132418034 ecr 1132417734], length 0
-IP 127.0.0.1.6379 > 127.0.0.1.52759: Flags [F.], seq 1, ack 1, win 342, options [nop,nop,TS val 1132418034 ecr 1132418034], length 0

[...]

```

**Comment by fxlb** [comment]
3 last commits (or more) are missing in the fold.

**Comment by adarqui** [comment]
Sorry about that. :/ I think it's good now. I force pushed it back up to resp-dev-squashed with those commits added.

I think it should be good now. If not, I apologize in advance!

Thanks,

Andrew

**Comment by fxlb** [comment]
@adarqui 
Merged. Thanks for your work and your patience.

**Comment by fxlb** [comment]
@adarqui There is a problem on Solaris. Any idea ?
(https://buildfarm.opencsw.org/buildbot/builders/tcpdump-solaris10-amd64/builds/894)
```
Failed test: resp_3

57c57
< IP 127.0.0.1.52767 > 127.0.0.1.6379: Flags [P.], seq 1:39, ack 1, win 342, options [nop,nop,TS val 1132419549 ecr 1132419549], length 38: RESP null
---
> IP 127.0.0.1.52767 > 127.0.0.1.6379: Flags [P.], seq 1:39, ack 1, win 342, options [nop,nop,TS val 1132419549 ecr 1132419549], length 38: RESP empty
```

**Comment by fxlb** [comment]
Thank you @guyharris to find the fix very quickly.

**Comment by adarqui** [comment]
Thanks everyone!

**Comment by infrastation** [comment]
Nice job everyone. I am sorry for not having the momentum to handle this a year ago.

**Pull request closed without merging**
