### PR TITLE
MPTCP: Print 'Length' inside mptcp options

### PR DESCRIPTION
**Pull request by mruprich**
Current mptcp parser prints 'mptcp <Subtype>...' but RFC 8684 in Section 3. states that the format should be 'mptcp <Length> <Subtype>...'

I added the printing of the Length field as just a plain number, it seems to me that having 'mptcp Length 8 dss...' is a little bit disruptive.

### CODE REVIEW

**Comment by infrastation** [comment]
I was fixing buildbot configuration and restarting it at the time, if you squash the changes together it should retry the failed builds.

**Comment by mruprich** [comment]
@infrastation will do, thanks ;)

**Comment by mruprich** [comment]
@infrastation Hi, is the linux-aarch64 build error related to this PR? Thanks.

**Comment by infrastation** [comment]
No, it was a build script bug, which should hopefully be fixed by now.

**Comment by mruprich** [comment]
Hi, did anyone have any time to take a look at this? Thanks.

**Comment by mruprich** [comment]
Any update on this PR? Is there anything I can do to help with this?

**Comment by fxlb** [comment]
Could you rebase the PR on the top of master to redo all checks?

**Comment by infrastation** [comment]
Which specific part of Section 3 do you refer to?

**Comment by mruprich** [comment]
Sorry, seems like the first comment here got somehow stripped of some parts. It should have been like this:
Current mptcp parser prints 'mptcp Subtype ...' but RFC 8684 in Section
3. states that the format should be 'mptcp Length Subtype ...'

This is in the 3.  MPTCP Operations: An Overview -> Figure 3: MPTCP Option Format

**Comment by fxlb** [comment]
Merged, thank you!

**Pull request merged**
