### PR TITLE
Printing function for VXLAN GPE and NSH

### PR DESCRIPTION
**Pull request by bugyo**
This pull request is the repost of #487.
I squashed the verbose commit logs and rebased on the current master branch.
Would it be acceptable?

----

I Added verbose output for encapsulated packets with Generic Protocol Extension for VXLAN and Network Service Header.
they are described in following documents.

draft-quinn-vxlan-gpe-04.txt ( https://datatracker.ietf.org/doc/draft-quinn-vxlan-gpe/ )
draft-ietf-sfc-nsh-01.txt ( http://datatracker.ietf.org/doc/draft-ietf-sfc-nsh/ )
I think that researchers and developers related on Service Function Chaining will be happy if this patch is merged.

### CODE REVIEW

**Comment by infrastation** [comment]
draft-quinn-vxlan-gpe has been replaced with draft-ietf-nvo3-vxlan-gpe, does this code still stand for the latest revision?

**Comment by bugyo** [comment]
Yes, draft-ietf-nvo3-vxlan-gpe did not change the alignment of the header. Only the latest draft allows MPLS payload. I will commit a supported version.

**Comment by bugyo** [comment]
OK, now this pull request stands for the latest draft.

**Comment by infrastation** [comment]
Thank you, please allow some time for somebody to review in better detail. Meanwhile it would help if you could add a `make check` test case for it based on a sample packet capture.

**Comment by bugyo** [comment]
I also think that. I will add a test case and am waiting for some comments. Thank you.

**Comment by bugyo** [comment]
OK, I added a test case for my code.

**Comment by fxlb** [comment]
Build test: there are some warnings.
See `CONTRIBUTING` file part `4)`.

**Comment by fxlb** [comment]
Please update according to f25ed1f812ec8eddf9702d54f16e5aa15c371271.

**Comment by bugyo** [comment]
OK, I updated the code according to f25ed1f. Thank you.

**Comment by bugyo** [comment]
This pull request merged a upa's contribution which enable to display MD-type 2 NSH Header.

**Comment by fxlb** [comment]
Thanks, I will review in a few days.

**Comment by fxlb** [comment]
Some comments after a first review:

A. A bound test was missing in `print-vxlan.c`, added in 20c9007debe6a04176c02842ec4d97641b67efb1. Also added a #define for more readability. Please update `print-vxlan-gpe.c` in accordance with this commit.
Same for print-nsh.c.

B. print-nsh.c, line 89: The loop  is only for MD Type == 0x01 ?

C. Which code for MD Type == 0x02?

D. print-nsh.c, line 90: before extracting 32 bits you need to check for remaining data with f.e. ND_TCHECK2.

E. The usual way to print the VXLAN-GPE flags is:
```
static const struct tok vxlan_gpe_flags [] = {
    { 0x08, "I" },
    { 0x04, "P" },
    { 0x01, "O" },
    { 0, NULL }
};

[...]

    ND_PRINT((ndo, "flags [%s], ", bittok2str_nosep(vxlan_gpe_flags,
              "none", flags)));
```
Same for print-nsh.c.

F. print-nsh.c, line 109 & print-vxlan-gpe.c, line 98: Is it truncated? Not just invalid next protocol?

G. As the output depend on vflag, you should add more test cases with f.e.:
```
nsh-over-vxlan-gpe nsh-over-vxlan-gpe.pcap nsh-over-vxlan-gpe.out -t
nsh-over-vxlan-gpe-v nsh-over-vxlan-gpe.pcap nsh-over-vxlan-gpe-v.out -t -v
nsh-over-vxlan-gpe-vv nsh-over-vxlan-gpe.pcap nsh-over-vxlan-gpe-vv.out -t -vv
nsh-over-vxlan-gpe-vvv nsh-over-vxlan-gpe.pcap nsh-over-vxlan-gpe-vvv.out -t -vvv
```
H. print-nsh.c & print-vxlan-gpe.c: Remove space at end of line 5.

I. `X < ndo->ndo_vflag` tests: We usually test with: `ndo->ndo_vflag > X`

**Comment by bugyo** [comment]
First, Thank you for your review.

>A. A bound test was missing in print-vxlan.c, added in 20c9007. Also added a #define for more readability. Please update print-vxlan-gpe.c in accordance with this commit.
Same for print-nsh.c.

Sure. I will correct.

>B. print-nsh.c, line 89: The loop is only for MD Type == 0x01 ?
>C. Which code for MD Type == 0x02?

This code is for both MD Types 0x01 and 0x02. They have the same syntax except for MD Type 0x01 fixes Length field == 0x06. But I noticed that the draft specifies the format for Optional Variable Length Metadata. I will support it.

>E. The usual way to print the VXLAN-GPE flags is:

I will correct my code using bittok2str_nosep.

>F. print-nsh.c, line 109 & print-vxlan-gpe.c, line 98: Is it truncated? Not just invalid next protocol?

Yes, It just invalid or unknown next protocol.
I will correct my code like print-gre.c.

>G. As the output depend on vflag, you should add more test cases with f.e.:

Yes.

>H. print-nsh.c & print-vxlan-gpe.c: Remove space at end of line 5.

Yes.

>I. X < ndo->ndo_vflag tests: We usually test with: ndo->ndo_vflag > X

OK.

**Comment by bugyo** [comment]
I fixed my code according to the comment.

**Comment by fxlb** [comment]
Thanks. Please give me a few days to check once again.

**Comment by fxlb** [comment]
Merged with space editing.
Thanks for your work and patience!

**Pull request closed without merging**
