### PR TITLE
Remove local bpf_dump(), supplied by libpcap since version 0.6

### PR DESCRIPTION
**Pull request by fxlb**

### CODE REVIEW

**Comment by infrastation** [comment]
Apparently, OpenBSD libpcap does not implement `bpf_dump()`.

**Comment by fxlb** [comment]
It seems that OpenBSD libpcap don't supply bpf_dump()...

**Comment by fxlb** [comment]
Keep running the tests to see if it's the only OS, before closing.

**Comment by infrastation** [comment]
Well, maybe then the best thing to do would be to add a comment somewhere to say "the only known reason to keep this check/code is that OpenBSD libpcap does not implement bpf_dump()" or something like that.

**Comment by fxlb** [comment]
Yes, done.

**Pull request closed without merging**
