### PR TITLE
Geneve: update format_opt_class

### PR DESCRIPTION
**Pull request by deiger**
Per https://www.iana.org/assignments/nvo3/nvo3.xhtml

### CODE REVIEW

**Comment by infrastation** [comment]
The change looks good. Do you have an example packet capture file with a vendor-specific option class?

**Comment by fxlb** [comment]
The first line of the commit message should be : `Geneve: Update format_opt_class`

**Comment by deiger** [comment]
> The change looks good. Do you have an example packet capture file with a vendor-specific option class?

Sorry for the late reply. Here is a sample packet:
```
0000   42 01 c0 a8 64 03 42 01 c0 a8 64 fe 08 00 45 00   B...d.B...d...E.
0010   00 74 00 00 40 00 02 11 2e 27 c0 a8 64 fe c0 a8   .t..@....'..d...
0020   64 03 f0 a3 17 c1 00 60 00 00 0a 00 08 00 00 00   d......`........
0030   00 00 01 32 01 01 80 00 00 d1 01 32 02 04 08 00   ...2.......2....
0040   00 0d c0 a8 64 02 00 00 00 00 00 00 00 00 01 32   ....d..........2
0050   03 02 00 00 00 00 00 00 12 34 45 00 00 28 12 36   .........4E..(.6
0060   00 00 40 06 1f 46 c0 a8 64 02 c0 a8 64 01 0b 5b   ..@..F..d...d..[
0070   1f 90 6a d2 56 30 50 9f ba 54 50 00 02 00 6d ae   ..j.V0P..TP...m.
0080   00 00                                             ..
```
The Geneve header is from `002a` to `0059`.

**Comment by deiger** [comment]
> Thank you. Could you please prepare a pcap file with a single packet with the new option, and add a new test for the new code path (see `tests/TESTLIST`)?

Added.

**Comment by infrastation** [comment]
Thank you.

**Pull request merged**
