### PR TITLE
Add support for IS-IS Node/Prefix SIDs as per rfc 8667

### PR DESCRIPTION
**Pull request by hannesgredler**
This time patch applied to a clean fork of upstream. sorry for the inconvenience.

### CODE REVIEW

**Comment by hannesgredler** [comment]
What is this appveyor check doing ? - it complains about errors vs. stock gcc passes just fine.

**Comment by fxlb** [comment]
`uint` type seems unkown for some reason: `error C2065: 'uint': undeclared identifier`.
You should try: `s/uint/u_int/`.
$ git grep -n '\<uint\>'
print-isoclns.c:1906:       uint sid;
print-isoclns.c:2335:isis_print_router_cap_subtlv(netdissect_options *ndo, const uint8_t *tptr, uint tlen)
print-isoclns.c:2363:           uint range, sid;

**Comment by hannesgredler** [comment]
ok, replaced;

**Comment by guyharris** [comment]
> What is this appveyor check doing ? - it complains about errors vs. stock gcc passes just fine.

It complains about builds on Windows with MSVC vs. stock GCC - on UN\*X? - passes just fine.

Not every development environment defines a `uint` type.  For the current master branch, however, all the C99 uint*N*_t (and int*N*_t) types are guaranteed to be defined.

**Comment by fxlb** [comment]
Some issue(s) :
https://travis-ci.org/github/the-tcpdump-group/tcpdump/builds/670602725?utm_source=github_status

**Comment by fxlb** [comment]
Rebased in one commit, merged, thank you !

**Comment by hannesgredler** [comment]
Thanks Francois-Xavier !

**Pull request closed without merging**
