### PR TITLE
Factor BGP NLRI printing into a reusable function

### PR DESCRIPTION
**Pull request by fenner**
The implementations of MP_REACH_NLRI and MP_UNREACH_NLRI attributes had duplicate implementations for each supported AFI/SAFI, and were out of sync (SAFNUM_RT_ROUTING_INFO had no handling for UNREACH).

The fact of having two implementations for each AFI/SAFI makes it easy to forget one when working on the other, as evidenced by my discovery of a locally-implemented printer that had only MP_REACH but not MP_UNREACH code.  Having a common implementation will eliminate this problem for people adding new AFI/SAFI support (and, of course, when fixing bugs in the existing implementation)

Coverage of the new code against existing tests is https://github.com/fenner/tcpdump/wiki/bgp_print_nlri-code-coverage-with-existing-tests .

### CODE REVIEW

**Comment by fxlb** [comment]
There is a warning:
```
./print-bgp.c: In function ‘bgp_attr_print’:
./print-bgp.c:1785:11: warning: unused variable ‘path_id’ [-Wunused-variable]
     u_int path_id = 0;
           ^
```
See: https://travis-ci.org/the-tcpdump-group/tcpdump/jobs/521900320
Please fix and rebase.

**Comment by fenner** [comment]
Sorry about that. May I recommend making Travis use -Werror to help make problems like this more obvious?

**Comment by fenner** [comment]
I only just noticed this is 3 commits, I’ll squash and push again. The Travis build failure was a transient homebrew issue.

**Comment by fxlb** [comment]
Merged. Thank you.

**Comment by fxlb** [comment]
> May I recommend making Travis use -Werror to help make problems like this more obvious?

Done with 06a4f18db6702efa6771daa8853beec7c800c421.

**Comment by fenner** [comment]
> > May I recommend making Travis use -Werror to help make problems like this more obvious?
> 
> Done with [06a4f18](https://github.com/the-tcpdump-group/tcpdump/commit/06a4f18db6702efa6771daa8853beec7c800c421).

Thanks!

**Pull request merged**
