### PR TITLE
autoconf: search for gethostbyaddr() in libnetwork

### PR DESCRIPTION
**Pull request by davidkaroly**
This is needed for building on Haiku.

### CODE REVIEW

**Comment by guyharris** [comment]
I don't see any calls to `socket()` in the tcpdump source; is the problem that some library *called* by tcpdump calls `socket()`?

**Comment by infrastation** [comment]
It would help to know the exact steps to reproduce the problem, please see `CONTRIBUTING.md`. See also #996, maybe you would like to update it with more detail.

**Comment by davidkaroly** [comment]
> I don't see any calls to `socket()` in the tcpdump source; is the problem that some library _called_ by tcpdump calls `socket()`?

It turns out that `-lnetwork` is needed for `getservent()`

Should we do something like this? in `AC_LBL_LIBRARY_NET`:

```
AC_SEARCH_LIBS(getservent, network)
```

**Comment by guyharris** [comment]
Is `-lnetwork` needed for `gethostbyaddr()`?

**Comment by davidkaroly** [comment]
> Is `-lnetwork` needed for `gethostbyaddr()`?

yes that one as well

**Comment by davidkaroly** [comment]
Sorry about the back and forth, I just noticed the latest commit on master.

We can simply add `network` to the search libs list for `gethostbyaddr` - I guess this is the cleanest way of adding `-lnetwork`

**Pull request merged**
