### PR TITLE
adding tests for ipoib (IP over Infiniband)

### PR DESCRIPTION
**Pull request by Sashan**
</snip>
    empty-pcap                         : passed
    empty-pcapng                       : passed
    dns-badcookie                      : passed
    dns-badvers                        : passed
    lldp-app-priority                  : passed
    dns-uri                            : passed
    vsock-1                            : TEST FAILED(exit 256)
    ipoib                              : passed
</snip>

### CODE REVIEW

**Comment by Sashan** [comment]
this adds test case for stuff in PR #751

**Comment by fxlb** [comment]
In you commit message:
```
> vsock-1                            : TEST FAILED(exit 256)
```
What libpcap version are you using ?

**Comment by fxlb** [comment]
Author field too long in your commit. Please only "Name <email>".

**Comment by Sashan** [comment]
> In you commit message:
> 
> ```
> > vsock-1                            : TEST FAILED(exit 256)
> ```
> 
> What libpcap version are you using ?

libpcap 1.8.1

**Comment by fxlb** [comment]
> libpcap 1.8.1
For other dev, I suggest you to use libpcap HEAD of the-tcpdump-group:master to avoid 'TEST FAILED' message(s).

Rebased, commit message updated, merged, thank you.

**Pull request closed without merging**
