### PR TITLE
Moved source port equal BCM_LI_PORT to bottom of long if else chain.

### PR DESCRIPTION
**Pull request by jonaschianu-CIENA**
BCM_LI_SHIM (BCM_LI_PORT) value is set to 49152, therefore when the source port is 49152, it does not matter what the true destination is, it defaults to Broadcom. So tcpdump interprets any packet with source UDP port of 49152 as BCM_LI_SHIM (Broadcom). Ports 49152+, by definition are ephemeral ports so it's totally reasonable that BFD is using that source port for their packets. To prevent BFD packets from being wrongly identified as BCM_LI_SHIM packets, the "else if" statement has been moved to bottom of long chain.

### CODE REVIEW

**Comment by jonaschianu-CIENA** [comment]
[abc.zip](https://github.com/the-tcpdump-group/tcpdump/files/11130602/abc.zip)

Before Changes:
```
$tcpdump -r abc.pcap -xxx -vvv
reading from file abc.pcap, link-type EN10MB (Ethernet), snapshot length 262144
09:58:19.559328 IP (tos 0xe0, ttl 255, id 40257, offset 0, flags [DF], proto UDP (17), length 52)
    11.11.11.2.49152 > 11.11.11.1.3784: [no cksum]
    BCM-LI-SHIM: direction unused, pkt-type unknown, pkt-subtype untagged, li-id 525080
     (invalid)
        0x0000:  e46d 7f54 b908 9443 4dc0 1785 8100 e00b
        0x0010:  0800 45e0 0034 9d41 4000 ff11 b17e 0b0b
        0x0020:  0b02 0b0b 0b01 c000 0ec8 0020 0000 20c8
        0x0030:  0318 8000 0001 8000 0001 0001 86a0 0001
        0x0040:  86a0 0000 0000
09:58:19.647228 IP (tos 0xe0, ttl 255, id 40340, offset 0, flags [DF], proto UDP (17), length 52)
    11.11.11.2.49152 > 11.11.11.1.3784: [no cksum]
    BCM-LI-SHIM: direction unused, pkt-type unknown, pkt-subtype untagged, li-id 525080
     (invalid)
        0x0000:  e46d 7f54 b908 9443 4dc0 1785 8100 e00b
        0x0010:  0800 45e0 0034 9d94 4000 ff11 b12b 0b0b
        0x0020:  0b02 0b0b 0b01 c000 0ec8 0020 0000 20c8
        0x0030:  0318 8000 0001 8000 0001 0001 86a0 0001
        0x0040:  86a0 0000 0000
```

After Changes
```
$ tcpdump -r abc.pcap -xxx -vvv 
reading from file abc.pcap, link-type EN10MB (Ethernet)
15:28:19.559328 IP (tos 0xe0, ttl 255, id 40257, offset 0, flags [DF], proto UDP (17), length 52)
    11.11.11.2.49152 > 11.11.11.1.bfd-control: [no cksum] BFDv1, length: 24
	Control, State Up, Flags: [Control Plane Independent], Diagnostic: No Diagnostic (0x00)
	Detection Timer Multiplier: 3 (300 ms Detection time), BFD Length: 24
	My Discriminator: 0x80000001, Your Discriminator: 0x80000001
	  Desired min Tx Interval:     100 ms
	  Required min Rx Interval:    100 ms
	  Required min Echo Interval:    0 ms
	0x0000:  e46d 7f54 b908 9443 4dc0 1785 8100 e00b
	0x0010:  0800 45e0 0034 9d41 4000 ff11 b17e 0b0b
	0x0020:  0b02 0b0b 0b01 c000 0ec8 0020 0000 20c8
	0x0030:  0318 8000 0001 8000 0001 0001 86a0 0001
	0x0040:  86a0 0000 0000
15:28:19.647228 IP (tos 0xe0, ttl 255, id 40340, offset 0, flags [DF], proto UDP (17), length 52)
    11.11.11.2.49152 > 11.11.11.1.bfd-control: [no cksum] BFDv1, length: 24
	Control, State Up, Flags: [Control Plane Independent], Diagnostic: No Diagnostic (0x00)
	Detection Timer Multiplier: 3 (300 ms Detection time), BFD Length: 24
	My Discriminator: 0x80000001, Your Discriminator: 0x80000001
	  Desired min Tx Interval:     100 ms
	  Required min Rx Interval:    100 ms
	  Required min Echo Interval:    0 ms
	0x0000:  e46d 7f54 b908 9443 4dc0 1785 8100 e00b
	0x0010:  0800 45e0 0034 9d94 4000 ff11 b12b 0b0b
	0x0020:  0b02 0b0b 0b01 c000 0ec8 0020 0000 20c8
	0x0030:  0318 8000 0001 8000 0001 0001 86a0 0001
	0x0040:  86a0 0000 0000
```

**Comment by fxlb** [comment]
After the question on the mailing list: "Does anyone see a problem with this change? (Answer on PR page.)", there was no answer.
Thus I propose to merge this PR next week.

**Comment by fxlb** [comment]
1. Add a test file (first packet of abc.pcap)
2. Fold the body of the commit message.

**Comment by fxlb** [comment]
3. State in the commit message that BFD is only an example of the problem.

**Comment by fxlb** [comment]
Thank you!

**Pull request merged**
