### PR TITLE
Print EIGRP when carried in IPv6

### PR DESCRIPTION
**Pull request by lunn**
The EIGRP protocol can be carried in IPv4 or IPv6. The basic protocol
remains the same. So call the EIGRP dissector for IPv6 packets with
IPPROTO_EIGRP.

### CODE REVIEW

**Comment by infrastation** [comment]
Have you got any sample capture for EIGRP in IPv6?

**Comment by lunn** [comment]
[ipv6-eigrp.pcap.zip](https://github.com/the-tcpdump-group/tcpdump/files/1296992/ipv6-eigrp.pcap.zip)

**Comment by mcr** [comment]
Andrew Lunn <notifications@github.com> wrote:
    > ipv6-eigrp.pcap.zip

Yes, but please add it to tests/ and TESTLIST and capture and read the output and
make sure it make sense, and make sure "make check" works.

--
]               Never tell me the odds!                 | ipv6 mesh networks [
]   Michael Richardson, Sandelman Software Works        | network architect  [
]     mcr@sandelman.ca  http://www.sandelman.ca/        |   ruby on rails    [

**Comment by infrastation** [comment]
Thank you!

**Pull request merged**
