### PR TITLE
A bunch of changes that we got accumulated in the FreeBSD tree.

### PR DESCRIPTION
**Pull request by glebius**
Fixes compilation at high warning levels.

### CODE REVIEW

**Comment by guyharris** [comment]
Please split this into separate pull requests for the `addrtostr.c` change (which we'll probably do differently - there's a *reason* why we made the loop index unsigned; see the changelog for `addrtostr.c`) and the pfsync enhancement.

**Comment by glebius** [comment]
I have hard time with github. Initially I created pull request for addrtostr.c. Then I pushed commit for pfsync into my fork, and it automatically was added to the pull request.

**Comment by guyharris** [comment]
You probably need separate branches for each change.  (I keep separate *source trees* for each change I'm working on.)

**Comment by glebius** [comment]
I see. I will try to redo this.

**Comment by infrastation** [comment]
Pushing a commit to a branch makes it appear on the pull request, that is the traditional behaviour on GitHub. This way the requestors can address some of the points raised and then get back to the original discussion. Separate branches usually do the job.

**Pull request closed without merging**
