### PR TITLE
ICMPv6: Fix the Node Information flags

### PR DESCRIPTION
**Pull request by nreillyqnx**
The fetching of the Node Info flags field uses GET_BE_U_2() which will byte swap, but the constants were also byte swapped with htons() when defined. Remove the byte swapping at definition time to get the field to decode properly.

I also noticed that NI_SUPTYPE_FLAG_COMPRESS and NI_FQDN_FLAG_VALIDTTL were defined byte swapped, but these are unused, so remove them.

### CODE REVIEW

**Comment by fxlb** [comment]
Thanks for the proposal.
Note that the byte swap is not always done (big endian host).
Please add at least one pcap file with some NI_NODEADDR_FLAG* flags to print.
See CONTRIBUTING.md, section 6) Add/update tests
```
   Any new/updated fields in a dissector must be present in a `sample.pcap` file
   and the corresponding output file.

   Configuration is set in `tests/TESTLIST`.
   [...]
```

**Comment by fxlb** [comment]
The commit title should be `ICMPv6: Fix the Node Information flags`.

**Comment by fxlb** [comment]
Todo:
1) Remove the commit [Merge branch 'the-tcpdump-group:master' into master] with `git reset --hard @^`.
2) Rebase to one commit:  `git rebase -i @~2` with a commit message like:
```
ICMPv6: Fix the Node Information flags

Don't use htons() when defining the constants because the flags
field is already eventually swapped by fetching with GET_BE_U_2().
Add a test file with various NI_NODEADDR_FLAG* flags.
```
2) Rebase on top of main branch: `git rebase <official>/master`

**Comment by nreillyqnx** [comment]
I'm sorry but I have no idea what I'm doing with git and github. I've tried following your instructions but I don't think it worked.

**Comment by fxlb** [comment]
I will have a look.

**Comment by fxlb** [comment]
It seems better. Let the checks run...

**Comment by fxlb** [comment]
Thank you!

**Pull request merged**
