### PR TITLE
BFD: add SBFD support (RFC7880 and RFC7881)

### PR DESCRIPTION
**Pull request by fenner**
Add support for SBFD on UDP port 7784.  SBFD is different
in that packets from the reflector will be sent with *source*
port 7784; in all other BFD mechanisms, it is only the
destination port that matters.  For SBFD print-udp.c has to
check both source and destination port.

### CODE REVIEW

**Comment by infrastation** [comment]
(Rebased on the current master to see up-to-date CI results.)

**Comment by infrastation** [comment]
Bill, would you mind if I update this to print "S-BFD" instead of "Sbfd"? Other than that, the proposed changes seem to match the spec exactly.

**Comment by infrastation** [comment]
Thank you for making this contribution!

**Comment by fenner** [comment]
> Bill, would you mind if I update this to print "S-BFD" instead of "Sbfd"? Other than that, the proposed changes seem to match the spec exactly.

Hi Denis, thank you very much for merging this and for this naming improvement.  I apologize for not having been able to reply quickly, and I appreciate that you made the updates.

**Pull request merged**
