### PR TITLE
require suitable printf()

### PR DESCRIPTION
**Pull request by infrastation**
Do not merge yet, but feel free to criticise.  If these changes still hold in a couple weeks, I will rebase and merge.

At first let's see if this passes all CI (especially Appveyor).

### CODE REVIEW

**Comment by infrastation** [comment]
This discusses `printf()`, but the actual test is for `snprintf()`, so the messages and the comments need a bit of clarification.

**Comment by infrastation** [comment]
This now incorporates all the fixups I intended to make.

**Comment by infrastation** [comment]
For reference, here are examples of the output:
* Autoconf on Solaris 9
  ```
  checking for vsnprintf... yes
  checking for snprintf... yes
  checking whether snprintf is suitable... no
  configure: error: The snprintf(3) implementation in this libc is not suitable,
  tcpdump would not work correctly even if it managed to compile.
  ```
* Autoconf on Linux
  ```
  checking for vsnprintf... yes
  checking for snprintf... yes
  checking whether snprintf is suitable... yes
  ```
* CMake on Linux
  ```
  -- Looking for vsnprintf
  -- Looking for vsnprintf - found
  -- Looking for snprintf
  -- Looking for snprintf - found
  -- Performing Test SUITABLE_SNPRINTF
  -- Performing Test SUITABLE_SNPRINTF - Success
  ``

**Comment by fxlb** [comment]
Should we cherry-pick it in the 4.99 branch?

**Comment by infrastation** [comment]
Yes, as discussed on the list.

**Pull request merged**
