### PR TITLE
Olsr fixes

### PR DESCRIPTION
**Pull request by fhuberts**

### CODE REVIEW

**Comment by fxlb** [comment]
Thanks fotr the patches.
Could you send samples pcap files showing the outputs for the tests directory used by `make check`?

**Comment by fhuberts** [comment]
What do you mean?
I have a sample pcap file for the situation that is fixed. It has 1packet with a relevant HNA

**Comment by fhuberts** [comment]
Before:
```
14:13:10.538099 IP (tos 0x10, ttl 1, id 25245, offset 0, flags [DF], proto UDP (17), length 100)
    172.29.175.220.olsr > 255.255.255.255.olsr: [udp sum ok] OLSRv4, seq 0xce93, length 72
	HNA Message (0x04), originator 172.31.175.220, ttl 255, hop 0
	  vtime 288.000s, msg-seq 0x6ce5, length 28
	  Advertised networks (total 0)
	    0.0.0.0/4294967295, 10.175.220.0/24
	Hello-LQ Message ...
```

After:
```
14:13:10.538099 IP (tos 0x10, ttl 1, id 25245, offset 0, flags [DF], proto UDP (17), length 100)
    172.29.175.220.olsr > 255.255.255.255.olsr: [udp sum ok] OLSRv4, seq 0xce93, length 72
	HNA Message (0x04), originator 172.31.175.220, ttl 255, hop 0
	  vtime 288.000s, msg-seq 0x6ce5, length 28
	  Advertised networks (total 2)
	    Smart-Gateway: LINKSPEED IPV4 IPV4-NAT 10000/10000, 10.175.220.0/24
	Hello-LQ Message ...
```

**Comment by fxlb** [comment]
We use tests directory to do regression tests on the dissection of captured packets, by running tcpdump against a savefile `sample.pcap`, created with `-w` option and comparing the results with a text file `sample.out` giving the expected results.

Any new/updated field in a protocol must have a `sample.pcap` file and the corresponding output file.

Configuration is set in `tests/TESTLIST`.
Each line in this file has the following format:
```
test-name     sample.pcap     sample.out      tcpdump-options
```
the `sample.out` file can be build by:
`(cd tests && ../tcpdump -n -r sample.pcap tcpdump-options > sample.out)`

**Comment by fhuberts** [comment]
I don't believe there currently are tests that cover this.
And the field is not new, it was implemented incompletely in tcpdump.

**Comment by fxlb** [comment]
I mean new to tcpdump support.

**Comment by fxlb** [comment]
For historical reasons, not all decoders have theses regression tests.

**Comment by fhuberts** [comment]
I can add a test for this case but I sure hope you don't expect me to cover all of the olsr decoder...

**Comment by fxlb** [comment]
Thanks.
No, I don't expect that.  It is a beginning...

**Comment by fhuberts** [comment]
added the test

**Comment by fxlb** [comment]
I get this warning on Debian Jessie, gcc 4.9.1 and on Travis-CI.
Please, could you try:
```
touch .devel
./configure
make
touch print-olsr.c
make -s
```
Do you get more warnings?

**Comment by fhuberts** [comment]
When I do that I do get the type-punned warning.
I'll try to get rid of it

**Comment by fhuberts** [comment]
should be fixed now

**Comment by fxlb** [comment]
Coiuld you update your patch for `master` branch. the `4.7` branch is read only.

**Comment by fxlb** [comment]
I mean your Pull Request.

**Comment by fxlb** [comment]
There is a problem (see at the top):
'wants to merge `85 commits` into the-tcpdump-group:`tcpdump-4.7` from fhuberts:olsr-fixes'
It must be:
'wants to merge `3 commits` into the-tcpdump-group:`master` from fhuberts:olsr-fixes'

**Comment by fhuberts** [comment]
I closed this and opened #456

**Comment by fhuberts** [comment]
github workflow sucks

**Pull request closed without merging**
