### PR TITLE
Add dissector for ICMP Interface Identification Object

### PR DESCRIPTION
**Pull request by Ishaangandhi**
The ICMP dissector currently assumes all ICMP multi-part extensions are MPLS extensions. This change correctly identifies these extensions as Multi-part extensions, not MPLS, and dissects the interface information object, as specified in RFC 5837.

### CODE REVIEW

**Comment by Ishaangandhi** [comment]
One of the Travis jobs (https://travis-ci.org/github/the-tcpdump-group/tcpdump/jobs/732601177) are buggy (keeps on rerunning the same command). You might need to restart it.

**Comment by Ishaangandhi** [comment]
@ infrastation I wanted to write a gentle bump on this PR

**Comment by infrastation** [comment]
Thank you for preparing this work. I will not be able to do a complete review in the next few weeks, so somebody else might do that first.

However, if I was making this change I would consider splitting it into two focused commits: one with only the changes that spell ICMP multipart instead of MPLS in the existing code, and another with only the new implementation of code point 2 and the associated test.

Also please terminate `icmp_interface_identification_role_values[]` with `{ 0, NULL }` in case some code in future uses it with a value greater than 3.

**Comment by Ishaangandhi** [comment]
Hi, @infrastation. Would you prefer I split into two focussed commits before performing a code review?

**Comment by infrastation** [comment]
Please try to do that if you can, and rebase on the current master branch.

**Comment by Ishaangandhi** [comment]
Is f94b3b4 and ca46014 ok?

**Comment by Ishaangandhi** [comment]
Hi, gently bumping this again.

**Comment by fxlb** [comment]
> Also please terminate `icmp_interface_identification_role_values[]` with `{ 0, NULL }` in case some code in future uses it with a value greater than 3.

+1

**Comment by fxlb** [comment]
Please 
1) Rebase on top of the-tcpdump-group:master.
2) Fix the conflicts.

**Comment by Ishaangandhi** [comment]
> Please
> 
> 1. Rebase on top of the-tcpdump-group:master.
> 2. Fix the conflicts.

Done

**Review by mcr — APPROVED** [review]

**Comment by Ishaangandhi** [comment]
@fxlb This PR has been removed and all checks have passed. Can you remove the "needs work" label and merge it?

**Comment by fxlb** [comment]
Thank you!

**Pull request merged**
