### PR TITLE
EAPOL-MKA (MACsec Key Agreement protocol) support added.

### PR DESCRIPTION
**Pull request by plorinquer**
Hello,

This pull request adds support for the EAPOL MKA (MACsec Key Agreement) protocol, which is defined in  
 the [802.1X-2010](http://standards.ieee.org/getieee802/download/802.1X-2010.pdf) IEEE standard.

Thanks in advance for your review.

### CODE REVIEW

**Comment by guyharris** [comment]
@mcr OK, it now builds, after bringing it up to date with the current state of tcpdump.  Do we want test files?

**Comment by mcr** [comment]
> @mcr OK, it now builds, after bringing it up to date with the current state of tcpdump. Do we want test files?

Always⸘

**Comment by fxlb** [comment]
Rebased on top of the-tcpdump-group:master.

**Comment by fxlb** [comment]
There are some error:
```
./print-eap.c:611:73: error: use of undeclared identifier 'tptr'
       uint16_t param_set_body_len = get_parameter_set_body_length(ndo, tptr + 2);
                                                                        ^
./print-eap.c:624:31: error: use of undeclared identifier 'tptr'
                   GET_BE_U_4(tptr + 4),
                              ^
./print-eap.c:625:31: error: use of undeclared identifier 'tptr'
                   GET_BE_U_4(tptr + 8));
                              ^
                                                  ^
[...]

fatal error: too many errors emitted, stopping now [-ferror-limit=]
20 errors generated.
--- print-eap.o ---
*** [print-eap.o] Error code 1

make: stopped in /tmp/cirrus-ci-build
1 error

make: stopped in /tmp/cirrus-ci-build

Exit status: 2
```

**Comment by plorinquer** [comment]
Hello,

Unfortunately, I haven't been able to work on this for a very long time, and I no longer have the means to reproduce the tests carried out at the time.

I suggest to close this PR. The code could possibly be reviewed and updated/rewritten if anyone wishes to work on this protocol.

Best regards.

**Pull request closed without merging**
